# Generated by Django 5.2.4 on 2025-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_user_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_servings',
            field=models.IntegerField(default=1),
        ),
    ]
