# Generated by Django 5.2.4 on 2025-07-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_quantity_float_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
