# Generated by Django 5.2.4 on 2025-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desired_servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
