# Generated by Django 5.2.4 on 2025-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_desired_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='notes',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
