# Generated by Django 5.2.4 on 2025-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ingredient_notes_ingredient_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='use_fractions',
            field=models.BooleanField(default=True),
        ),
    ]
